//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COGOLineFeatures {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class COGOLineDialog : global::System.Configuration.ApplicationSettingsBase {
        
        private static COGOLineDialog defaultInstance = ((COGOLineDialog)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new COGOLineDialog())));
        
        public static COGOLineDialog Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastUsedParams {
            get {
                return ((string)(this["LastUsedParams"]));
            }
            set {
                this["LastUsedParams"] = value;
            }
        }
    }
}
