//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateFeatureService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreateFeatureService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;type&quot;: &quot;csv&quot;,
        ///  &quot;name&quot;: &quot;KauaiPOI&quot;,
        ///  &quot;useBulkInserts&quot;: true,
        ///  &quot;sourceUrl&quot;: &quot;&quot;,
        ///  &quot;locationType&quot;: &quot;coordinates&quot;,
        ///  &quot;maxRecordCount&quot;: 2000,
        ///  &quot;geocodeServiceUrl&quot;: &quot;https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer&quot;,
        ///  &quot;sourceCountry&quot;: &quot;us&quot;,
        ///  &quot;sourceLocale&quot;: &quot;en&quot;,
        ///  &quot;addressFields&quot;: { &quot;City&quot;: &quot;PLACENAME&quot; },
        ///  &quot;standardizedFieldNames&quot;: {
        ///    &quot;Address&quot;: &quot;Address or Place&quot;,
        ///    &quot;Address2&quot;: &quot;Address2&quot;,
        ///    &quot;Address3&quot;: &quot;Address3&quot;,
        ///    &quot;City&quot;: &quot;City&quot;,
        ///    &quot;Region&quot;: &quot;State&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PointOfInterest_json {
            get {
                return ResourceManager.GetString("PointOfInterest_json", resourceCulture);
            }
        }
    }
}
