//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPToolInspector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPToolInspector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///  &lt;script src=&quot;https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js&quot;&gt;
        ///  &lt;/script&gt;
        ///  &lt;body&gt;
        ///    &lt;pre class=&quot;prettyprint&quot;&gt;
        ///      &lt;code class=&quot;language-cs&quot;&gt;
        ///        $codehere$
        ///      &lt;/code&gt;
        ///    &lt;/pre&gt;
        ///  &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        public static string HtmlTemplate {
            get {
                return ResourceManager.GetString("HtmlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///```
        ///Language:              $progLanguageShort$  
        ///Subject:               $allSubjects$  
        ///Contributor:           $contributor$  
        ///Organization:          $organization$  
        ///Date:                  $processingDate$  
        ///ArcGIS Pro:            $proVersion$  
        ///Visual Studio:         $visualStudioVersion$  
        ///.NET Target Framework: $targetFramework$  
        ///```
        ///
        ///## ProSnippets for Geoprocessing Tools
        ///
        ///This document provides ProSnippets that aid in calling any ArcGIS Pro Geoprocessing tool from within your Add-in.
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProSnippets {
            get {
                return ResourceManager.GetString("ProSnippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   
        ///```
        ///Language:              $progLanguageShort$  
        ///Subject:               $subject$  
        ///Contributor:           $contributor$  
        ///Organization:          $organization$  
        ///Date:                  $processingDate$  
        ///ArcGIS Pro:            $proVersion$  
        ///Visual Studio:         $visualStudioVersion$  
        ///.NET Target Framework: $targetFramework$  
        ///```
        ///
        ///&lt;!-- Auto generated page --&gt;
        ///
        ///$snippets$
        ///
        ///.
        /// </summary>
        public static string ProSnippetTemplate {
            get {
                return ResourceManager.GetString("ProSnippetTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Home](../wiki)
        ///
        ///### GP Tool ProSnippets: $subject$
        ///
        ///$sidebarTitles$
        ///.
        /// </summary>
        public static string SidebarTemplate {
            get {
                return ResourceManager.GetString("SidebarTemplate", resourceCulture);
            }
        }
    }
}
