//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatePointsAlongLine3D {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<CIMSymbolReference xsi:type=\'typens:CIMSymbolReference\' xmlns:xsi=\'http://www.w3" +
            ".org/2001/XMLSchema-instance\' xmlns:xs=\'http://www.w3.org/2001/XMLSchema\' xmlns:" +
            "typens=\'http://www.esri.com/schemas/ArcGIS/2.2.0\'><Symbol xsi:type=\'typens:CIMLi" +
            "neSymbol\'><SymbolLayers xsi:type=\'typens:ArrayOfCIMSymbolLayer\'><CIMSymbolLayer " +
            "xsi:type=\'typens:CIMCharacterMarker\'><Enable>true</Enable><ColorLocked>false</Co" +
            "lorLocked><AnchorPointUnits>Relative</AnchorPointUnits><AngleX>0</AngleX><AngleY" +
            ">0</AngleY><DominantSizeAxis3D>Y</DominantSizeAxis3D><OffsetX>0</OffsetX><Offset" +
            "Y>0</OffsetY><OffsetZ>0</OffsetZ><RotateClockwise>false</RotateClockwise><Rotati" +
            "on>180</Rotation><Size>25</Size><BillboardMode3D>FaceNearPlane</BillboardMode3D>" +
            "<MarkerPlacement xsi:type=\'typens:CIMMarkerPlacementAlongLineSameSize\'><Primitiv" +
            "eName/><AngleToLine>true</AngleToLine><Offset>0</Offset><ControlPointPlacement>W" +
            "ithMarkers</ControlPointPlacement><CustomEndingOffset>0</CustomEndingOffset><End" +
            "ings>WithHalfGap</Endings><OffsetAlongLine>0</OffsetAlongLine><PlacementTemplate" +
            " xsi:type=\'typens:ArrayOfDouble\'><Double>60</Double></PlacementTemplate></Marker" +
            "Placement><CharacterIndex>33</CharacterIndex><Depth3D>0</Depth3D><FontFamilyName" +
            ">ESRI Dimensioning</FontFamilyName><FontStyleName>Regular</FontStyleName><FontTy" +
            "pe>Unspecified</FontType><ScaleX>1</ScaleX><Symbol xsi:type=\'typens:CIMPolygonSy" +
            "mbol\'><SymbolLayers xsi:type=\'typens:ArrayOfCIMSymbolLayer\'><CIMSymbolLayer xsi:" +
            "type=\'typens:CIMSolidStroke\'><Enable>true</Enable><ColorLocked>false</ColorLocke" +
            "d><CapStyle>Round</CapStyle><JoinStyle>Round</JoinStyle><LineStyle3D>Strip</Line" +
            "Style3D><MiterLimit>10</MiterLimit><Width>0.1</Width><CloseCaps3D>false</CloseCa" +
            "ps3D><Color xsi:type=\'typens:CIMRGBColor\'><Values xsi:type=\'typens:ArrayOfDouble" +
            "\'><Double>255</Double><Double>255</Double><Double>255</Double><Double>100</Doubl" +
            "e></Values></Color></CIMSymbolLayer><CIMSymbolLayer xsi:type=\'typens:CIMSolidFil" +
            "l\'><Enable>true</Enable><ColorLocked>false</ColorLocked><Color xsi:type=\'typens:" +
            "CIMRGBColor\'><Values xsi:type=\'typens:ArrayOfDouble\'><Double>0</Double><Double>0" +
            "</Double><Double>0</Double><Double>100</Double></Values></Color></CIMSymbolLayer" +
            "></SymbolLayers><ThumbnailURI/><UseRealWorldSymbolSizes>false</UseRealWorldSymbo" +
            "lSizes></Symbol><VerticalOrientation3D>false</VerticalOrientation3D><ScaleSymbol" +
            "sProportionally>true</ScaleSymbolsProportionally><RespectFrame>true</RespectFram" +
            "e></CIMSymbolLayer></SymbolLayers><ThumbnailURI/><UseRealWorldSymbolSizes>false<" +
            "/UseRealWorldSymbolSizes></Symbol><MinScale>0</MinScale><MaxScale>0</MaxScale><M" +
            "inDistance>0</MinDistance><MaxDistance>0</MaxDistance></CIMSymbolReference>")]
        public string lineSymbol2D {
            get {
                return ((string)(this["lineSymbol2D"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<CIMSymbolReference xsi:type=\'typens:CIMSymbolReference\' xmlns:xsi=\'http://www.w3" +
            ".org/2001/XMLSchema-instance\' xmlns:xs=\'http://www.w3.org/2001/XMLSchema\' xmlns:" +
            "typens=\'http://www.esri.com/schemas/ArcGIS/2.4.0\'>\r\n  <Symbol xsi:type=\'typens:C" +
            "IMLineSymbol\'>\r\n    <SymbolLayers xsi:type=\'typens:ArrayOfCIMSymbolLayer\'>\r\n    " +
            "  <CIMSymbolLayer xsi:type=\'typens:CIMObjectMarker3D\'>\r\n        <Enable>true</En" +
            "able>\r\n        <ColorLocked>false</ColorLocked>\r\n        <Overprint>false</Overp" +
            "rint>\r\n        <AnchorPointUnits>Relative</AnchorPointUnits>\r\n        <AngleX>0<" +
            "/AngleX>\r\n        <AngleY>90</AngleY>\r\n        <DominantSizeAxis3D>Z</DominantSi" +
            "zeAxis3D>\r\n        <OffsetX>0</OffsetX>\r\n        <OffsetY>0</OffsetY>\r\n        <" +
            "OffsetZ>0</OffsetZ>\r\n        <RotateClockwise>false</RotateClockwise>\r\n        <" +
            "Rotation>0</Rotation>\r\n        <Size>10</Size>\r\n        <BillboardMode3D>None</B" +
            "illboardMode3D>\r\n        <MarkerPlacement xsi:type=\'typens:CIMMarkerPlacementAlo" +
            "ngLineSameSize\'>\r\n          <PrimitiveName/>\r\n          <AngleToLine>true</Angle" +
            "ToLine>\r\n          <Offset>0</Offset>\r\n          <ControlPointPlacement>WithMark" +
            "ers</ControlPointPlacement>\r\n          <CustomEndingOffset>0</CustomEndingOffset" +
            ">\r\n          <Endings>WithMarkers</Endings>\r\n          <OffsetAlongLine>0</Offse" +
            "tAlongLine>\r\n          <PlacementTemplate xsi:type=\'typens:ArrayOfDouble\'>\r\n    " +
            "        <Double>16</Double>\r\n          </PlacementTemplate>\r\n        </MarkerPla" +
            "cement>\r\n        <ModelURI>CIMPATH=ObjectMarker3D/7c4179308a2a7b08527a68d39c6672" +
            "d8.dat</ModelURI>\r\n        <Width>10</Width>\r\n        <Depth>10</Depth>\r\n       " +
            " <TintColor xsi:type=\'typens:CIMRGBColor\'>\r\n          <Values xsi:type=\'typens:A" +
            "rrayOfDouble\'>\r\n            <Double>0</Double>\r\n            <Double>0</Double>\r\n" +
            "            <Double>0</Double>\r\n            <Double>100</Double>\r\n          </Va" +
            "lues>\r\n        </TintColor>\r\n        <IsRestricted>false</IsRestricted>\r\n       " +
            " <UseAnchorPoint>true</UseAnchorPoint>\r\n      </CIMSymbolLayer>\r\n    </SymbolLay" +
            "ers>\r\n    <ThumbnailURI/>\r\n    <UseRealWorldSymbolSizes>false</UseRealWorldSymbo" +
            "lSizes>\r\n  </Symbol>\r\n  <MinScale>0</MinScale>\r\n  <MaxScale>0</MaxScale>\r\n  <Min" +
            "Distance>0</MinDistance>\r\n  <MaxDistance>0</MaxDistance>\r\n</CIMSymbolReference>")]
        public string lineSymbol3D {
            get {
                return ((string)(this["lineSymbol3D"]));
            }
        }
    }
}
